[package]
name = "linky_decoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teleinfo-nom = "0.1.1"
serialport = "4.2.0"
